### ISSUE TITLE
Driver.java:65: error: cannot find symbol

### ISSUE THREAD

**Issue by tianzhijia** [denisleahy/roche-radius-calculator#1]
Operating system: Mac OS 10.14.5

`java --version`
> java 12.0.1 2019-04-16
> Java(TM) SE Runtime Environment (build 12.0.1+12)
> Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

The version 2.1 works well on my mac, However, the version 3.0 doesn't.
`java Driver.java`
>  Driver.java:65: error: cannot find symbol
> 	PolarFrame aPolarFrame = new PolarFrame("Polar coordinate calculator");
> 	^
>   symbol:   class PolarFrame
>   location: class Driver
> Driver.java:65: error: cannot find symbol
> 	PolarFrame aPolarFrame = new PolarFrame("Polar coordinate calculator");
> 	                             ^
>   symbol:   class PolarFrame
>   location: class Driver
> Driver.java:68: error: cannot find symbol
> 	    MainFrame aFrame = new MainFrame("Roche Radius Calculator", aPolarFrame);
> 	    ^
>   symbol:   class MainFrame
>   location: class Driver
> Driver.java:68: error: cannot find symbol
> 	    MainFrame aFrame = new MainFrame("Roche Radius Calculator", aPolarFrame);
> 	                           ^
>   symbol:   class MainFrame
>   location: class Driver
> 4 errors
> error: compilation failed

I'm not familiar with Java. Did I choose a proper version of JAVA or how to fix the bug? 

Problem solved:
```
javac Driver.java
java Driver
```
